// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-VTqmnUPrqxPcZzetHB32W9yEYIv_JY',
    appId: '1:1088210608352:web:9d166ecfc9d0ee3690f085',
    messagingSenderId: '1088210608352',
    projectId: 'rosella-63332',
    authDomain: 'rosella-63332.firebaseapp.com',
    storageBucket: 'rosella-63332.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2orU3-tjokzEABYBUx6c9balt1TE2p-k',
    appId: '1:1088210608352:android:c1b495abc1f0dad090f085',
    messagingSenderId: '1088210608352',
    projectId: 'rosella-63332',
    storageBucket: 'rosella-63332.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPaH42AOnHjPjugzO_b9ZZg3fjR19Q5zM',
    appId: '1:1088210608352:ios:dbe20f1772543d6690f085',
    messagingSenderId: '1088210608352',
    projectId: 'rosella-63332',
    storageBucket: 'rosella-63332.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPaH42AOnHjPjugzO_b9ZZg3fjR19Q5zM',
    appId: '1:1088210608352:ios:dbe20f1772543d6690f085',
    messagingSenderId: '1088210608352',
    projectId: 'rosella-63332',
    storageBucket: 'rosella-63332.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC-VTqmnUPrqxPcZzetHB32W9yEYIv_JY',
    appId: '1:1088210608352:web:722b18c18228d19090f085',
    messagingSenderId: '1088210608352',
    projectId: 'rosella-63332',
    authDomain: 'rosella-63332.firebaseapp.com',
    storageBucket: 'rosella-63332.firebasestorage.app',
  );
}
